version: '3.7'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      POSTGRES_USER: user 

