version: '3.7'
services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      POSTGRES_USER: user 
  api: 
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    environment: 
      DB_HOST: localhost
      DB_PORT: 5000
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - "./src:/app/src"
    ports:
      - "3000:3000"
    networks:
      - default
